CREATE TABLE CLIENT_MASTER(CLIENTNO VARCHAR(6) PRIMARY KEY CHECK(CLIENTNO LIKE 'C%'),NAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(30),ADDRESS2 VARCHAR(30),CITY VARCHAR(15),
PINCODE NUMERIC(8),STATE VARCHAR(15),BALDUE NUMERIC(10,2));

CREATE TABLE PRODUCT_MASTER (PRODUCTNO VARCHAR(6) PRIMARY KEY CHECK(PRODUCTNO LIKE 'P%'),DESCRIPTION VARCHAR(15) NOT NULL,PROFITPERC NUMERIC(4,2) NOT NULL,
UNITMEASURE VARCHAR(15) NOT NULL,QNTYONHAND NUMERIC(8) NOT NULL,REORDERLVL NUMERIC(8) NOT NULL,
SELLPRICE NUMERIC(8,2) NOT NULL CHECK(SELLPRICE!=0),COSTPRICE NUMERIC(8,2) NOT NULL CHECK(COSTPRICE!=0));

CREATE TABLE SALESMAN_MASTER (SALESMANNO VARCHAR(6) PRIMARY KEY CHECK(SALESMANNO LIKE 'S%'),SALEMANNAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(30) NOT NULL,ADDRESS2 VARCHAR(30),CITY VARCHAR(20),
PINCODE NUMERIC(8) ,STATE VARCHAR(20),SALAMT NUMERIC(8,2)NOT NULL CHECK(SALAMT!=0),TGTTOGET NUMERIC(6,2) NOT NULL,YIDSALES NUMERIC(6,2) NOT NULL,REMARKS VARCHAR(30));

CREATE TABLE SALES_ORDER (ORDERNO VARCHAR(6) PRIMARY KEY CHECK(SALESMANNO LIKE 'O%'),CLIENTNO VARCHAR(6) FOREIGN KEY(CLIENTNO) REFERENCES CLIENT_MASTER (CLIENTNO),ORDERDATE DATE,DELYADDR VARCHAR(25),SALESMANNO VARCHAR(6) FOREIGN KEY(SALESMANNO) REFERENCES SALESMAN_MASTER (SALESMANNO),DELYTYPE CHAR(1) CHECK(DELYTYPE='P' OR DELYTYPE='F'),
BILLEDYN CHAR(1) CHECK(BILLEDYN='Y' OR BILLEDYN='N'),DELYDATE DATE,ORDERSTATUS VARCHAR(10) CHECK(ORDERSTATUS='In process'OR ORDERSTATUS='Fulfilled'OR ORDERSTATUS='Backorder'OR ORDERSTATUS='Cancelled'));

CREATE TABLE SALES_ORDER_DETAILS (ORDERNO VARCHAR(6) FOREIGN KEY(ORDERNO) REFERENCES SALES_ORDER(ORDERNO),PRODUCTNO VARCHAR(6) FOREIGN KEY(PRODUCTNO) REFERENCES PRODUCT_MASTER(PRODUCTNO),QTYORDERED NUMERIC(8),QTYDISP NUMERIC(8),
PRODUCTRATE NUMERIC(10,2),PRIMARY KEY(ORDERNO,PRODUCTNO));

INSERT INTO CLIENT_MASTER(CLIENTNO,NAME,CITY,PINCODE,STATE,BALDUE)VALUES('C00001','Ivan Bayross','Mumbai',400054,'Maharashtra',15000);
INSERT INTO PRODUCT_MASTER VALUES('P00001','T-Shirts',5,'Piece',200,50,350,250);
INSERT INTO SALESMAN_MASTER VALUES('S00001','Aman','A/14','Worli','Mumbai',400002,'Maharashtra',3000,100,50,'Good');
INSERT INTO SALES_ORDER(ORDERNO,ORDERDATE,CLIENTNO,DELYTYPE,BILLEDYN,SALESMANNO,DELYDATE,ORDERSTATUS)
VALUES('O19001','12-june-02','C00001','F','N','S00001','20-july-02','In Process');
INSERT INTO SALES_ORDER_DETAILS(ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE) VALUES('O19001','P00001',4,4,525);
--Answer following queries with the help of above schema :
SELECT NAME FROM CLIENT_MASTER;
SELECT *FROM CLIENT_MASTER WHERE CITY='Mumbai';
SELECT *FROM PRODUCT_MASTER WHERE SELLPRICE >2000 AND SELLPRICE<5000;
SELECT NAME,CITY,STATE FROM CLIENT_MASTER WHERE STATE<>'Maharashtra';
SELECT *FROM CLIENT_MASTER WHERE CLIENTNO='C0001'OR CLIENTNO='C0002';
UPDATE PRODUCT_MASTER SET SELLPRICE=1150.50 WHERE SELLPRICE='1.44 drive';
DELETE FROM CLIENT_MASTER WHERE CLIENTNO='C0005';
SELECT *FROM CLIENT_MASTER WHERE CITY LIKE '__a%';
SELECT COUNT(*) FROM PRODUCT_MASTER WHERE SELLPRICE>=1500;
--10. Display qtyordered, qtydisp and balancedqty (not in table)
SELECT QtyOrdered,QtyDisp AS Balancedqty FROM Sales_Order_Details;



--Write commands to do the following:
ALTER TABLE CLIENT_MASTER ADD PRIMARY KEY(CLIENTNO);
ALTER TABLE CLIENT_MASTER ADD [COLUMN] PHONENO;


